### ISSUE TITLE
Add back `mintPolicy`

### ISSUE THREAD

**Issue by samuelWilliams99** [mlabs-haskell/seabug-contracts#13]
The `mintPolicy` field is currently ignored, and not present in the NFTs we have minted via BPI.
This task is across several repos - to fix the minting process to include this field, and fix the metadata to not ignore it.
Blocked until debugging of frontend is complete.

**Comment by Guilherme775** [comment]
This issue has already been resolved in these PRs/Commits:

[PR](https://github.com/mlabs-haskell/seabug-contracts/pull/5)
[Commit](https://github.com/mlabs-haskell/seabug-contracts/pull/5/commits/314661f80158656b5a37137bbad1c3d2eb5bfd8d)
and [Commit](https://github.com/mlabs-haskell/seabug-contracts/pull/5/commits/753ac07744c0343d02a2cf78d0ceb68ffd9e45bf)
