### ISSUE TITLE
Remove some debug logs

### ISSUE THREAD

**Issue by samuelWilliams99** [mlabs-haskell/seabug-contracts#33]
Given this project has been tricky to get working, there are a lot of unnecessary debug logs with minimal description. This task is to either remove those that are not needed, or add context to those that are so the console isn't constantly a mess of random information.

**Comment by rynoV** [comment]
Addressed by https://github.com/mlabs-haskell/seabug-contracts/pull/5/commits/12fc59b711c111c444f66a93de6d8d367e90c150
