### ISSUE TITLE
Fix wallet connection logic

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/seabug-contracts#36]
`seabug-contracts` doesn't currently expose any function for connecting the wallet. This function was present prior to moving Seabug offchain logic out of the main CTL repo. It either needs to get added back or we need to change how the frontend connects to the wallet.

Original implementation:
- https://github.com/Plutonomicon/cardano-transaction-lib/blob/77b1517ceb6e320498b95407af7bdd87902f41b4/npm-packages/cardano-transaction-lib-seabug/index.js
- https://github.com/Plutonomicon/cardano-transaction-lib/blob/77b1517ceb6e320498b95407af7bdd87902f41b4/seabug_contracts/Seabug.purs

**Comment by samuelWilliams99** [comment]
is this a blocker for getting the code to Volo? @rynoV appears to have been able to test still?

**Comment by rynoV** [comment]
@samuelWilliams99 It shouldn't be blocker, the main features are working without the wallet connection logic. Not sure exactly what the logic was used for though

**Comment by nrutledge** [comment]
If this still works as it did previously, the user will get prompted automatically to connect their Nami wallet as soon as the first CTL query runs (i.e., on page load). In that case, it's definitely not a blocker.

However, I don't know how this works with multiple wallets. We really want the user to be able to click the wallet icon at the top/right of the page and connect to their desired wallet.

**Comment by rynoV** [comment]
> the user will get prompted automatically to connect their Nami wallet as soon as the first CTL query runs (i.e., on page load)

Just checked and this is the case (I unwhitelisted localhost and the prompt showed up when I reloaded)

**Comment by Guilherme775** [comment]
Solved in #43
